name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ci:
        name: Lint, Check & Build
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            # ---------- FRONTEND ---------- #
            - name: Install Frontend Dependencies
              working-directory: frontend
              run: npm ci

            - name: Lint Frontend
              working-directory: frontend
              run: npm run lint

            - name: Prettier Check Frontend
              working-directory: frontend
              run: npm run check

            - name: Build frontend
              if: github.event_name == 'push'
              working-directory: frontend
              run: npm run build

            # ---------- BACKEND ---------- #
            - name: Install backend dependencies
              working-directory: backend
              run: npm ci

            - name: Lint backend
              working-directory: backend
              run: npm run lint

            - name: Prettier check backend
              working-directory: backend
              run: npm run check

            - name: Build backend
              if: github.event_name == 'push'
              working-directory: backend
              run: npm run build
